name: deploy

on:
  push:
    branches: [master] # master 分支有 push 时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js v21.x
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'

      - name: Install
        run: yarn install # 安装依赖

      - name: Build
        run: yarn build # 打包

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4 # 使用部署到 GitHub pages 的 action
        with:
          publish_dir: ./dist # 部署打包后的 dist 目录
          # 希望部署的分支，默认gh-pages
          branch: gh-pages
          github_token: ${{ secrets.VUE3_WEBPACK_TEMPLATE_DEPLOY }} # secret 名
          #commit_message: Update Webpack5.x + Vue3.x Starter # 部署时的 git 提交信息，自由填写
