name: NodeJS with Webpack

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 21.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: yarn install # 安装依赖

      - name: Build
        run: yarn build

      - name: Upload to Deploy Server
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: master
          folder: ./dist
